[id="Managing_Content_Views_{context}"]
= Managing Content Views

{ProjectName} uses Content Views to allow your hosts access to a deliberately curated subset of content.
To do this, you must define which repositories to use and then apply certain filters to the content.

The general workflow for creating Content Views for filtering and creating snapshots is as follows:

. Create a Content View.
. Add one or more repositories that you want to the Content View.
. Optional: Create one or more filters to refine the content of the Content View.
For more information, see xref:Content_Filter_Examples_{context}[].
. Optional: Resolve any package dependencies for a Content View.
For more information, see xref:Resolving_Package_Dependencies_{context}[].
. Publish the Content View.
. Optional: Promote the Content View to another environment.
For more information, see xref:Promoting_a_Content_View_{context}[].
. Attach the content host to the Content View.

ifdef::client-content-dnf[]
If a repository is not associated with the Content View, the file `/etc/yum.repos.d/redhat.repo` remains empty and systems registered to it cannot receive updates.
endif::[]
ifdef::client-content-apt[]
If a repository is not associated with the Content View, the file `/etc/apt/sources.list.d/rhsm.sources` remains empty and systems registered to it cannot receive updates.
endif::[]

Hosts can only be associated with a single Content View.
To associate a host with multiple Content Views, create a composite Content View.
For more information, see xref:Creating_a_Composite_Content_View_{context}[].
