[id="Configuring_Direct_AD_Integration_with_GSS_Proxy_{context}"]
= Configuring direct AD integration with GSS-proxy

In the {Project} CLI, configure the direct Active Directory integration with GSS-proxy.

When using Active Directory (AD) as an external authentication source for {Project}, GSS-Proxy ensures enhanced security.
The traditional process of Kerberos authentication in Apache requires the Apache process to have read access to the keytab file.
GSS-Proxy allows you to implement stricter privilege separation for the Apache server by removing access to the keytab file while preserving Kerberos authentication functionality.

.Prerequisites
* Your AD user account has administrator privileges.

.Procedure
On your {ProjectServer}:

. Configure direct integration to AD.
For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/integrating_rhel_systems_directly_with_windows_active_directory/index#[].
. Enable IPA authentication in {Project}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --foreman-ipa-authentication=true
----
. Configure SSSD to map Group Policy Objects (GPOs) from AD to the `foreman` PAM service.
.. Add the following lines to the `/etc/sssd/sssd.conf` file:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
access_provider = ad
ad_gpo_access_control = enforcing
ad_gpo_map_service = +foreman
----
ifdef::satellite[]
+
For more information on GPOs, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/integrating_rhel_systems_directly_with_windows_active_directory/managing-direct-connections-to-ad_integrating-rhel-systems-directly-with-active-directory#applying-group-policy-object-access-control-in-rhel_managing-direct-connections-to-ad _Integrating RHEL systems directly with Windows Active Directory_.
endif::[]
.. Restart SSSD:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl restart sssd
----
. Configure GSS-Proxy for stricter privilege separation for the Apache server.
.. Determine the effective user ID of the Apache user:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# id {apache-user}
----
+
Apache user must not have access to the keytab file.
.. Create the `/etc/gssproxy/00-http.conf` file with the following content:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
[service/HTTP]
mechs = krb5
cred_store = keytab:/etc/gssproxy/http.keytab
cred_store = ccache:/var/lib/gssproxy/clients/krb5cc_%U
euid = __ID_of_Apache_User__
----
.. Set the correct SELinux context for the future keytab entry:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# semanage fcontext -a -s system_u -t krb5_keytab_t '/etc/gssproxy/http\.keytab'
----
.. Create a keytab entry:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# KRB5_KTNAME=FILE:/etc/gssproxy/http.keytab net ads keytab add HTTP -U administrator -d3 -s /etc/net-keytab.conf
# chown root.root /etc/gssproxy/http.keytab
# chmod 600 /etc/gssproxy/http.keytab
----
.. Start and enable the `gssproxy` service:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl restart gssproxy
# systemctl enable --now gssproxy
----
.. To configure the Apache server to use the `gssproxy` service, create a `systemd` drop-in file and add the following content to it:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mkdir -p /etc/systemd/system/httpd.service.d/
# vi /etc/systemd/system/httpd.service.d/gssproxy.conf
[Service]
Environment=GSS_USE_PROXY=1
----
.. Apply changes to the service:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl daemon-reload
----
.. Start and enable the `httpd` service:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl restart httpd
----

.Verification
Verify that SSO is working as expected. With a running Apache server, users making HTTP requests against the server are authenticated if the client has a valid Kerberos ticket.

. Destroy any existing Keberos ticket for your AD user:
+
[options="nowrap", subs="+quotes,attributes"]
----
# kdestroy _ad_user_
----
. Obtain a new Kerberos ticket for the AD user:
+
[options="nowrap", subs="+quotes,attributes"]
----
# kinit _ad_user_
----
+
. View the Kerberos ticket:
+
[options="nowrap", subs="+quotes,attributes"]
----
# klist
----
. View output from successful Kerberos authentication:
+
[options="nowrap", subs="+quotes,attributes"]
----
# curl -k -u : --negotiate https://__{foreman-example-com}/__users/extlogin
----
+
The `curl` command returns the following response:
+
[options="nowrap", subs="+quotes,attributes"]
----
<html><body>You are being <a href="https://__{foreman-example-com}/__users/4-ldapuserexample-com/edit">redirected</a>.</body></html>
----

.Next steps
* If you use the Internet Explorer browser, add {ProjectServer} to the list of Local Intranet or Trusted sites, and turn on the _Enable Integrated Windows Authentication_ setting.
See the Internet Explorer documentation for details.

ifndef::orcharhino[]
.Additional resources
* For information about configuring Firefox, see {RHELDocsBaseURL}9/html/configuring_authentication_and_authorization_in_rhel/configuring_applications_for_sso#Configuring_Firefox_to_use_Kerberos_for_SSO[Configuring Firefox to use Kerberos for single sign-on] in _{RHEL}{nbsp}9 Configuring authentication and authorization in RHEL_.

endif::[]